webtalk_init -webtalk_dir D:/Files/Codes/Verilog/CPU-uart/CPU.sim/sim_1/behav/xsim/xsim.dir/entertest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 29 15:40:37 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cbfb457b-acbb-4b79-8445-d6f5dd27f36e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "94ea0b2f4ab54f23b8f3f6831ef719a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "351 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11664_KB" -context "xsim\\usage"
webtalk_transmit -clientid 866832621 -regid "" -xml D:/Files/Codes/Verilog/CPU-uart/CPU.sim/sim_1/behav/xsim/xsim.dir/entertest_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Files/Codes/Verilog/CPU-uart/CPU.sim/sim_1/behav/xsim/xsim.dir/entertest_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Files/Codes/Verilog/CPU-uart/CPU.sim/sim_1/behav/xsim/xsim.dir/entertest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
