# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk.xci
# IP: The module: 'cpu_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk.xci
# IP: The module: 'cpu_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Files/Codes/Verilog/CPU-uart/CPU.srcs/sources_1/ip/cpu_clk/cpu_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
